### PR TITLE
Changed bower version number and added font path prefix

### PR DESCRIPTION
**Pull request by Nickersoft**
Corrections made after merge of #123.

@talbs @clintonb

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by talbs** [comment]
Please see my note in the previous PR - https://github.com/edx/ux-pattern-library/pull/123#discussion_r34681857.

**Comment by talbs** [comment]
Woah woah woah! You did not get thumbs from me on this. Please do not merge anything else into this repo without a proper review and approval!

**Comment by Nickersoft** [comment]
@talbs I'm sorry, I probably should have specified. I was under the impression the only blocker on this PR was the variable prefixing issue. I removed the ux-pattern-library prefix from the font path variable name (so it is currently $font-path). As a result, the only change that was merged in this PR was increasing the Bower version number to 0.0.1. Sorry again for not waiting. If the version number is an issue, I can open a PR reverting it.

**Comment by talbs** [comment]
@Nickersoft, thanks for clarifying. The reverting isn't necessary given the scope of this PR. In this repo and on this project, if someone is tagged as a reviewer, their review and approval is needed in order to merge. That may be different than your team's processes.

Hope that helps and thanks for the good contribution. Speaking of which, you need one more PR to add yourself to the list of contributors - https://github.com/edx/ux-pattern-library/blob/master/README.md#contributors :)

**Comment by Nickersoft** [comment]
@talbs I know.. I'll be sure to be more cautious next time. And I'll open that PR right now.

**Pull request merged**
