### PR TITLE
Removed pointer from progress bar hover.

### PR DESCRIPTION
**Pull request by dsjen**
## [UXPL-31](https://openedx.atlassian.net/browse/UXPL-31)

Removed pointer cursor from progress bar (in the forms section) on hovering.

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [x] Code review: @andy-armstrong 
- [x] Code review: @talbs 

### Post-review
- [ ] Squash commits

### CODE REVIEW

**Comment by andy-armstrong** [comment]
:+1: Nice!

**Comment by talbs** [comment]
:+1: Thanks for the fix and nice abstraction.

**Comment by talbs** [comment]
@dsjen, one thing I forgot to mention. This should have included a version change (for the Bower and NPM packages) as well as an update to the CHANGELOG. Mind making a follow-up PR to catch these?

I can walk you through them or the next steps of publishing when you're ready.

**Comment by dsjen** [comment]
@talbs -- of course!  Thanks for mentioning those.  I'll add them to my process notes.

**Pull request merged**
