### PR TITLE
Added self to AUTHORS

### PR DESCRIPTION
**Pull request by jamiefolsom**

### CODE REVIEW

**Comment by talbs** [comment]
Oh, sorry for the confusion @jamiefolsom. The OCD_minded ``pldoc:`` prefix is only needed for commits that affect Documentation Site code (aka Jekyll rendering and pldoc styling). The ``AUTHORS`` file is part of the bower package, so feel free to drop that prefix, amigo.

Thanks again for all of the help over the past couple of days.

**Comment by jamiefolsom** [comment]
@talbs makes sense. Amended!

**Comment by talbs** [comment]
Sweet! Making your help official, amigo.

**Comment by jamiefolsom** [comment]
Cheers, @talbs!

**Pull request merged**
