### PR TITLE
Release 0.12.2

### PR DESCRIPTION
**Pull request by clrux**
## Release notes

* Adds a custom Modernizr build to the Gulp workflow, configurable using `modernizr-config.json`

@andy-armstrong It seems like the `gh-pages` was quite a bit out of sync. Since my latest updates are only Gulp-related I will leave it up to you as to whether a merge to `gh-pages` is necessary. If not, I'll close this PR and leave it as it is.

### CODE REVIEW

**Comment by andy-armstrong** [comment]
@AlasdairSwan any explanation as to why this update to GitHub Pages would have such old commits? I'm fairly sure that your dropdown styling is already live on http://ux.edx.org/

**Comment by AlasdairSwan** [comment]
@andy-armstrong it's weird, you can see in the commits to the gh-pages that my release to update to version 0.11.0 was already merged, so I don't know why that commit is showing up again.

**Comment by AlasdairSwan** [comment]
And yes, the dropdown style updates are live on ux.edx.org already

**Comment by bjacobel** [comment]
I think this can be closed, right? Alisan's most recent release 0.16.0 removes modernizr & co. entirely. Is there code in this PR that should be resurfaced? I'm unfamiliar with what's going on here, looks like it was opened before I started at edx.

**Pull request closed without merging**
