### PR TITLE
FIX - Remove Local Sass (box-sizing) Compile Warnings

### PR DESCRIPTION
**Pull request by talbs**
This work adjusts Susy grid-settings to not look for/leverage Bourbon's now deprecated (due to it not being needed any more for browser support) ``box-sizing()`` mixin.

For more information see:

* Bourbon's box-sizing mixin - http://bourbon.io/docs/#box-sizing
* Susy custom support settings - http://susydocs.oddbird.net/en/latest/settings/#custom-support

- - -

##### Local compile output with warnings (on master)
```
10:51:03] Starting 'pldoc_styles'...
[10:51:03] Starting 'pldoc_scripts-lint'...
[10:51:03] Starting 'pldoc_images'...
[10:51:03] gulp-imagemin: Minified 0 images
[10:51:03] Finished 'pldoc_images' after 8.44 ms
[10:51:03] Finished 'pldoc_scripts-lint' after 70 ms
[10:51:03] Starting 'pldoc_scripts'...
[10:51:03] Finished 'pldoc_scripts' after 99 ms
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 395 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 399 of _src/pldoc/static/sass/_components.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 398 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 433 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 438 of _src/pldoc/static/sass/_components.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 437 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 70 of _src/pldoc/static/sass/_layouts.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 69 of _src/pldoc/static/sass/_layouts.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 80 of _src/pldoc/static/sass/_layouts.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 79 of _src/pldoc/static/sass/_layouts.scss

[10:51:04] Size main-ltr.css : 1.12 kB
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 395 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 399 of _src/pldoc/static/sass/_components.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 398 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 433 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 438 of _src/pldoc/static/sass/_components.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 437 of _src/pldoc/static/sass/_components.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 70 of _src/pldoc/static/sass/_layouts.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 69 of _src/pldoc/static/sass/_layouts.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of _src/vendor/bourbon/_bourbon-deprecated-upcoming.scss
	from line 12 of _src/vendor/susy/susy/output/support/_box-sizing.scss
	from line 40 of _src/vendor/susy/susy/output/support/_support.scss
	from line 12 of _src/vendor/susy/susy/output/shared/_output.scss
	from line 28 of _src/vendor/susy/susy/language/susy/_span.scss
	from line 80 of _src/pldoc/static/sass/_layouts.scss
	from line 24 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 36 of _src/vendor/susy/susy/language/susy/_grids.scss
	from line 23 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 75 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 66 of _src/vendor/breakpoint/_breakpoint.scss
	from line 74 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 21 of _src/vendor/susy/susy/language/susy/_breakpoint-plugin.scss
	from line 79 of _src/pldoc/static/sass/_layouts.scss

[10:51:05] Size main-rtl.css : 1.12 kB
[10:51:05] Finished 'pldoc_styles' after 1.52 s
[10:51:05] Starting 'jekyll-build'...
Configuration file: /Users/btalbot/edX/ux-pattern-library/_config.yml
            Source: /Users/btalbot/edX/ux-pattern-library
       Destination: /Users/btalbot/edX/ux-pattern-library/_site
      Generating...
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
[10:51:09] Finished 'jekyll-build' after 4 s
[10:51:09] Starting 'jekyll-build'...
Configuration file: /Users/btalbot/edX/ux-pattern-library/_config.yml
            Source: /Users/btalbot/edX/ux-pattern-library
       Destination: /Users/btalbot/edX/ux-pattern-library/_site
      Generating...
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
[10:51:12] Finished 'jekyll-build' after 3.97 s
[10:51:12] Starting 'browserSync'...
[10:51:13] Finished 'browserSync' after 104 ms
[10:51:13] Starting 'watch'...
[10:51:13] Finished 'watch' after 32 ms
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.58:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.58:3001
 ----------------------------------
[BS] Serving files from: ./_site
```

##### Local compile output without warnings (this work)
```
[11:03:38] Starting 'pldoc_styles'...
[11:03:38] Starting 'pldoc_scripts-lint'...
[11:03:38] Starting 'pldoc_images'...
[11:03:38] gulp-imagemin: Minified 0 images
[11:03:38] Finished 'pldoc_images' after 11 ms
[11:03:38] Finished 'pldoc_scripts-lint' after 74 ms
[11:03:38] Starting 'pldoc_scripts'...
[11:03:39] Finished 'pldoc_scripts' after 100 ms
[11:03:39] Size main-ltr.css : 1.12 kB
[11:03:40] Size main-rtl.css : 1.12 kB
[11:03:40] Finished 'pldoc_styles' after 1.47 s
[11:03:40] Starting 'jekyll-build'...
Configuration file: /Users/btalbot/edX/ux-pattern-library/_config.yml
            Source: /Users/btalbot/edX/ux-pattern-library
       Destination: /Users/btalbot/edX/ux-pattern-library/_site
      Generating...
                    done.
 Auto-regeneration: disabled. Use --watch to enable.
[11:03:44] Finished 'jekyll-build' after 3.75 s
[11:03:47] Starting 'browserSync'...
[11:03:48] Finished 'browserSync' after 72 ms
[11:03:48] Starting 'watch'...
[11:03:48] Finished 'watch' after 30 ms
[BS] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://10.0.1.58:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.1.58:3001
 ----------------------------------
[BS] Serving files from: ./_site
```

- - -

##### Reviwers

* [ ] FED/Local Set Up - @clrux

### CODE REVIEW

**Comment by talbs** [comment]
@clrux , mind giving this local gulp Sass warning fix a look?

**Comment by clrux** [comment]
Seems to do the trick. Although, when I click one of the sidebar links, the jump is kinda... jumpy. You seein' that?

**Comment by talbs** [comment]
@clrux, no, I'm not seeing that at all in either Chrome or FF on this branch. This change shouldn't affect any of that scrolling area/behavior.

**Comment by clrux** [comment]
@talbs Ok, could be something on my local.

:+1:

**Pull request merged**
