### PR TITLE
Sync Up - Certs + Pattern Library

### PR DESCRIPTION
**Pull request by talbs**
This work syncs up any static changes made when using the Pattern Library in the recent Web Certificates UI (https://github.com/edx/edx-platform/pull/7882). This includes:

* revising ``edx-pl`` source directory to be named ``pattern-library``
* removing unnecessary Open Sans typeface file formats + weights
* updating README
* making the ``pl`` namespace/prefix a bit more clear by changing it to ``pldoc`` in HTML, styling, and workflow tasks

- - -

**Reviewers**

* [ ] FED - @frrrances 
* [x] FED 2 - @clrux

### CODE REVIEW

**Comment by talbs** [comment]
@clrux and @frrrances, mind reviewing this work? Let me know if you need any context.

**Comment by clrux** [comment]
I think your renaming makes sense. I'm going to sync up my working branch with these as well so the rebase/merge is easier. Nice work. :+1:

**Comment by clrux** [comment]
Oh, also, I moved some of the scripts around so I'm wondering if it makes sense for this PR to wait on my PR? I'm not sure how important this one is. Rebasing mine on this one will be a nightmare, and visa versa.

**Comment by frrrances** [comment]
Good change!  :+1:

**Pull request merged**
