### PR TITLE
Setup: Use animate.css

### PR DESCRIPTION
**Pull request by talbs**
This work adds in the animate.css (https://github.com/daneden/animate.css and MIT license) animation utility classes/styling which can be used throughout our UI elements and JS logic for CS animation and transitions.

- - -

##### Reviewers
* [x] FED - @frrrances

### CODE REVIEW

**Comment by talbs** [comment]
@frrrances, mind taking a look at this extracurricular PR? My hope is that we get a lot of bang for our buck with this vendor utility down the road as a starter set of animations. The code is solid, well known/used, and triggering animations is pretty easy with classes on the DOM.

**Comment by talbs** [comment]
Oh, also, @frrrances, you'll need to run a ``bower install`` locally to get this library added in after switching to this branch.

**Comment by talbs** [comment]
@frrrances, a free coffee :gift:  of your choice is waiting at the end of this extracurricular review. :oP

**Comment by talbs** [comment]
@frrrances, rebased and ready if you have a moment (assuming this isn't a huge philosophical deal breaker to use a preset animation collection).

**Comment by frrrances** [comment]
That's a [go](https://media0.giphy.com/media/oLJ3zbbp4lX1u/200.gif) :+1:

**Comment by talbs** [comment]
[THhhhhhhhanks!](http://media.giphy.com/media/xco6aabVXUQzC/giphy.gif)

**Comment by talbs** [comment]
Also, you'll want to get get this new static component in your web certs repo manually by 1) doing a fresh bower install on your local pl repo and 2) copying and pasting the new component to your components repo dir.

**Pull request merged**
