### PR TITLE
Setup: Gulp Workflow (UX-1599)

### PR DESCRIPTION
**Pull request by talbs**
This work adds in basic gulp workflows for common local and pre-production tasks:

* gulp workflows for sass, compression, browser syncing, and jekyll
* abstraction for pattern library reference vs. pattern library element watching
* pattern library reference UI - directory set up, basic vendor + compile
* pattern library elements - directory set up, basic vendor + compile
* updates to README.md and .gitignore

### CODE REVIEW

**Comment by talbs** [comment]
NOTE: This work is based off of the jekyll-init work that is currently in https://github.com/edx/ux-pattern-library/pull/2.

**Comment by talbs** [comment]
@frrrances and @clrux, would you **both** mind reviewing this next Pattern Library PR?

I've based this off of https://github.com/edx/ux-pattern-library/pull/2, so it may be easier to look at diffs in the one commit deliberately added on this PR's branch - https://github.com/edx/ux-pattern-library/commit/c496c0e48e32db6896630ad94c714584c0ae4550

This is a workflow PR, so the things I need reviewed are:

* updates to the README.md file for the repo - start here for instructions/background on the gulp workflow (plz make sure "Typo Talbs" does not make an appearance);
* try installing/setting up the workflow yourself locally;
* try running the ``gulp`` command;
* try making some changes to a Sass file; drop an image in; or change a Jekyll template;
* make sure the light directory structure and Sass compilation skeletons I've added in match the standards we've set up [in general](https://github.com/edx/ux-pattern-library/wiki/Styleguide:-General),  [Sass/CSS](https://github.com/edx/ux-pattern-library/wiki/Styleguide:-Sass-&-CSS), and for [HTML](https://github.com/edx/ux-pattern-library/wiki/Styleguide:-HTML);
* confirm that my .gitignore and Jekyll config.yml files ignore the necessary files we don't want in the repo (the exceptions being compiled CSS for now - sadly, we need these here for github pages to find and serve when we push to the reference site).

Feel free to split the above tasks up if you want. I'd just like the FED brainstrust to be all onboard.
Thanks for the help!

- - -

FYI, @AlasdairSwan (thanks for the gulp assistance).

**Comment by talbs** [comment]
This has been rebased from a master and now only has the gulp config-related commits.

**Comment by clrux** [comment]
@talbs A few items from me:
* The `gulp` task runs the preview on port :3000. Since this differs from the `jekyll serve` command which serves on port :4000, it might be worth mentioning.
* It looks like you cover three different methods of running `gulp` but it was confusing to me. I just want to know which method we need for this project; I don't necessary want to know all other options. For example, if you're suggesting using the `gulp` package predefined for this pattern library, then I recommend only including instructions for that method.
* NIT: the folder named `pl`, while I understand it's shorthand for `pattern-library` I kind of just wish it said as much. `pl` is vague until you know what it represents.
* Question: I'm assuming the use of underscores (`_`) in the folder names are to force them to the top of the directory tree? Or are these required for Jekyll?

On the plus side, Gulp seems to fire up nicely. It's a little unclear that _all_ one needs to do is be in the repo and working directory and type `gulp` to initiate it. Having the references to the other two forms of serving was a little confusing. I noted this above.

Love the `.gitignore` file. So clean. So fresh. So freshclean.

**Comment by talbs** [comment]
@clrux, thanks. Per our convo in person this afternoon, I've updated the README file so only the ``gulp`` command is mentioned on running the local set up (to avoid confusion with the second Jekyll syntax option).

We're keeping on with the ``pl`` directory and naming convention for brevity's sake and as I explained, the underscore prefixed files are such to make sure Jekyll ignores them when moving them into the ``_site`` directory locally and when we publish to gh-pages.

Let me know if there's anything else or if this has "the thumbs".

**Comment by clrux** [comment]
:+1:

**Pull request merged**
