### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/edx-ux-team: I'm marking you as the owner of this repo.

**Comment by bjacobel** [comment]
:thumbsup:

**Comment by cpennington** [comment]
@bjacobel: Should I wait for review from someone else before I merge?

**Comment by bjacobel** [comment]
@cpennington in theory you need someone from a11y and UX to give thumbs but this change doesn't need review from them, I think.... go ahead and merge IMO.

**Pull request merged**
