### PR TITLE
Publish: Fonts/Icons/UI fixes and Prep for Theming/Packaging

### PR DESCRIPTION
**Pull request by talbs**
This work publishes the following:

* fixes icons to use Font Awesome Library
* fixes overflow problem with documentation site sidebar
* preps pattern source code for packaging + converts documentation site to use packaging structure
* prep for theming overrides
* simplifies font-face calls to modern browser support

### CODE REVIEW

**Comment by talbs** [comment]
@clrux, look good to send out to ux.edx.org?

**Comment by clrux** [comment]
@talbs Can we adjust the styles of the sidebar? There's a thick black line to the right of the present scrollbar that serves as the blue/black highlight for active sections. I wouldn't mind getting rid of this. Thoughts?

**Comment by talbs** [comment]
@clrux, you mean this guy (screengrab below)?

image

The black border is there to serve as depth, which maybe doesn't make sense anymore with a scrollbar. I'll remove it in a separate PR if you're cool with it. I'd prefer to keep the blue ``:target`` border to show the current element being focused on.

**Comment by clrux** [comment]
@talbs Hmm, try viewing the PL on your lappy toppy rather than your big monitor to see what I mean. Or see the below screenshot:

screen shot 2015-05-19 at 8 59 42 am

**Comment by talbs** [comment]
@clrux, ahh gotcha. Yeah I can remove that (or move it inside of the scroll) in a separate PR. I'll set one of those up in my spare time and will update this publish PR once that's merged in.

Thanks for the keen eye.

**Comment by clrux** [comment]
Sounds good, bud :+1:

**Comment by talbs** [comment]
@clrux, I've rebased this so it includes the sidebar fixes in #76. Look good to merge/publish this set of work?

**Comment by clrux** [comment]
Hmm, the sidebar black border is still there. I thought you got rid of that in #76?

**Comment by talbs** [comment]
Merging based on live thumbs from @clrux.

**Pull request merged**
