### PR TITLE
Changing links from # to edx.org

### PR DESCRIPTION
**Pull request by clrux**
@talbs This gets the link fixup to the site.

### CODE REVIEW

**Comment by talbs** [comment]
Does this have to go out now (vs being a part of an upcoming push)? If so, can you do the following?

* make sure its merged to master already
* rename this branch to start with ``clrux/publish-*`` (its easier to know what branches are for publishing this way)

**Comment by talbs** [comment]
If it can wait, I'd really recommend that as our previous publish branches/PRs have just taken the most recent set of commits that are the diff between ``master`` and ``gh-pages``. This would break that as there are other commits before this that haven't been merged to ``gh-pages`` yet.

**Comment by clrux** [comment]
It can wait. Maybe we can roll it in with the icons?

**Comment by talbs** [comment]
Yeah, that's fine. If you want to push before then (to get it out), you can make a PR of against ``gh-pages`` from the tip of ``master``.

Mind closing this and either doing that or waiting till we have icons?

**Comment by clrux** [comment]
Not necessary now. Will roll this update into the next publish branch.

**Pull request closed without merging**
