### PR TITLE
Publish: Icon & Copy Elements + Revisions + Simplifications

### PR DESCRIPTION
**Pull request by talbs**
This work pushes the following bits to the documentation site:

* color simplification
* button simplification/revision
* Element: icons (initial demo version)
* Element: copy
* PL doc site revisions: markup sync ups, copy element application
* Jekyll/Gulp workflow revisions: JS tasks, CSS compilation

### CODE REVIEW

**Comment by talbs** [comment]
@clrux, look good to you? If so, let's push this freshness to the site!

**Comment by clrux** [comment]
:+1: lgtm

**Comment by clrux** [comment]
Also: woot!

**Comment by talbs** [comment]
Totes woot! :truck:ing this to mergetown.

**Pull request merged**
