### PR TITLE
FIX - General Clean up of Sass Variables

### PR DESCRIPTION
**Pull request by talbs**
This work does some quick housekeeping of Pattern Library source Sass variables based on feedback and proactive formatting/dusting.

- - -

##### Reviewers

* [x] FED - @marcotuts or @frrrances

### CODE REVIEW

**Comment by talbs** [comment]
@frrrances or @marcotuts, mind giving this PR a quick once-over?

**Comment by marcotuts** [comment]
:+1: 

(I did wonder whether $baseline is more of a 'spacing baseline' aka 'spacebase'  aka :space_invader: :house: . No change necessary, though. :) )

**Comment by talbs** [comment]
> I did wonder whether $baseline is more of a 'spacing baseline'

@marcotuts, that's a good point. I'm not sure we use it for anything else but spacing in the PL. Should I change the variable name to make it clear its a spacing-focused property?

**Comment by frrrances** [comment]
:+1: (once you rebase :stuck_out_tongue_winking_eye: )

**Pull request merged**
