### PR TITLE
Publish: Tabs, stateful states

### PR DESCRIPTION
**Pull request by clrux**
@talbs This brings the tabs work into `gh-pages`, along with your stateful statefullness.

### CODE REVIEW

**Comment by talbs** [comment]
This is a long line of commits. Can you review that all of them are part of the work we want to bring in (or make sense to bring in since the last publish PR)?

**Comment by talbs** [comment]
I think the last publish PR that was merged was https://github.com/edx/ux-pattern-library/pull/26, right?

**Comment by clrux** [comment]
I think all of these are pertinent. They either deal with the colors/grayscale or the tabs. Then there's that CNAME one. That sound/look right?

**Comment by talbs** [comment]
@clrux, I thought we agreed to make a ``publish-*`` branch off of master to make a PR like this against gh-pages. Can you close this and do that, please?

**Pull request closed without merging**
