### PR TITLE
Elements: Buttons (futzing)

### PR DESCRIPTION
**Pull request by talbs**
This work visually tweaks some button properties and adds another elevated alt style to the catalog.

### CODE REVIEW

**Comment by talbs** [comment]
@clrux, what do you think?

**Comment by clrux** [comment]
Looks good. I like the addition and adjustments to the scales.

How are you feeling about MOAR buttons, though?

**Comment by clrux** [comment]
:+1: despite my previous comment.

**Comment by talbs** [comment]
Closing this in favor of https://github.com/edx/ux-pattern-library/pull/62 (which is up-to-date and tackles the same concerns).

**Pull request closed without merging**
