### PR TITLE
PL Doc: Correct Artifacts of Old Icon Rendering

### PR DESCRIPTION
**Pull request by talbs**
This work cleans up a few things that were missing at the end of https://github.com/edx/ux-pattern-library/pull/178, namely:

* syncing up the gulp ``production`` task
* updating the CHANGELOG file
* removing svg4everbody (used for the older SVG icon rendering method) as a bower dependencies

- - -

##### Reviewers

* [x] @AlasdairSwan

### CODE REVIEW

**Comment by talbs** [comment]
@AlasdairSwan, try running the following commands to make sure this works:

1. ``git clean -xfd'``
2. ``npm install``
3. ``bower install``
4. ``gulp`` and ``gulp production``

**Comment by AlasdairSwan** [comment]
@talbs that fixed the font issue. After running ``` gulp production ``` there are now only 4 modified files
```
modified:   public/css/main-ltr.css
modified:   public/css/main-ltr.css.map
modified:   public/css/main-rtl.css
modified:   public/css/main-rtl.css.map
```
Shouldn't we be gitignoring .map files in production?

**Comment by talbs** [comment]
> Shouldn't we be gitignoring .map files in production?

@AlasdairSwan, good point. Making that change now.

**Comment by AlasdairSwan** [comment]
Ship it :+1:

**Pull request merged**
