### PR TITLE
Cleanup after a time-sensitive update

### PR DESCRIPTION
**Pull request by clrux**
# Cleanup post 0.16.2

Version 0.16.2 brought in some time-sensitive color updates that developers needed to get unblocked. I needed to get it in by today (29 Jul 2016). After launch, I realized the JSON never got updated and I had duplicated the grays.

This cleans everything up.

## Preview

I am still unable to generate previews. IT has a ticket and has been working on it for quite some time. They are working on other things that need to happen before they can get back to my access. If a review is necessary, please check out the branch locally.

## Reviewers

- [ ] @bjacobel (familiar with previous work)

### CODE REVIEW

**Comment by bjacobel** [comment]
Little confused here - You merged your own release #347 (although I don't see a release for it on GitHub)?? That kind of stuff needs thumbs from other people.

We also don't do code changes in the same PR as a changelog/version bump, you should be following the release process outlined [here](https://openedx.atlassian.net/wiki/display/FEDX/UI+Toolkit+release+process) - make a PR with a code change, get thumbs, merge it, make a new PR with a changelog and version bump, get thumbs again, merge it and release to NPM, Bower and GitHub.

Time-sensitive or not, we've gotta follow protocol.

**Comment by bjacobel** [comment]
Code changes look fine, pull the changelog and the version bump stuff out of this and I'll give you thumbs. Then we can do a 0.16.3 release in another PR.

**Comment by clrux** [comment]
@bjacobel My mistake. I've removed the version stuff and changelog for now.

**Comment by bjacobel** [comment]
:thumbsup:

**Pull request merged**
