### PR TITLE
Fixed text cutting issue on default select

### PR DESCRIPTION
**Pull request by amir-qayyum-khan**
Hi 

Working for MIT.

- The default select box on chrome is working fine.
- But I was getting an issue on latest **firefox** on **mac os**. The text was cutting of from bottom. I fixed that issue and made this PR.
- The screenshots of issue is below:

@jamiefolsom @pdpinch

screen shot 2015-10-19 at 7 19 34 pm
screen shot 2015-10-19 at 7 19 58 pm 2

- After fix:
screen shot 2015-10-19 at 8 34 02 pm

### CODE REVIEW

**Comment by jamiefolsom** [comment]
@amir-qayyum-khan -- looks good to me -- @talbs, what do you think?

**Comment by talbs** [comment]
Hi, all. Sorry for the delay.

@amir-qayyum-khan, thanks for bringing this to our attention and proposing a solution - both are much appreciated.

Looking over the root issue, I think I want to solve this another way. In short, I don't think we should be placing a CSS ``height`` property on select fields. If you don't mind, I'm happy to take this under my wing, as I'll be improving some form styling shortly.

I've made an issue for this to help track and move this forward - https://github.com/edx/ux-pattern-library/issues/214

- - -

@amir-qayyum-khan and @jamiefolsom, is this bit of styling giving you folks trouble now in the platform/your current project. If so, let me know and I can try to help with your specific case while this issue is resolved separately.

Let me know if you have any concerns or questions. Thanks for the help and being active in the project!

**Comment by jamiefolsom** [comment]
Sounds good. Thanks @talbs!

**Comment by pdpinch** [comment]
@talbs I believe @amir-qayyum-khan implemented this in a CCX ui change that we plan to submit a PR for. 

If you want to get a preview, you can take a look at https://github.com/mitocw/edx-platform/pull/99 

We'll tag you when we submit the PR upstream. Probably early next week.

**Comment by talbs** [comment]
Wow, cool, @pdpinch. Yeah, please feel free to tag me with the Open edX team in that PR. Thanks for sharing and congrats on getting this feature made.

**Comment by amir-qayyum-khan** [comment]
@talbs sure, I just tag you in my edX PR https://github.com/edx/edx-platform/pull/10353.

In edX PR I have copied the rendered CSS from your pattern-library.

**Comment by talbs** [comment]
Thanks much. I'm going to close with the new issue created and the knowledge that we'll be tackling this shortly.

**Pull request closed without merging**
