### PR TITLE
Add a Gemfile and the github-pages gem

### PR DESCRIPTION
**Pull request by jamiefolsom**
Hey @talbs, 

I've found this useful on jekyll sites in the past. Feel free to use or not, of course!

**Problem**
The versions of jekyll and its dependencies can be updated by any developer; github pages is locked to specific versions.

**Solution** 
Adding a Gemfile to a jekyll repo and adding the github-pages gem to that Gemfile allows easy locking of said versions to those used on Github. ```bundle``` in the root generates a Gemfile.lock. Both can be checked into the repo.

**Context**
See: https://github.com/github/pages-gem

Thanks!

Jamie

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Hi @talbs,

I'm on a more up to date machine today, and the steps in the readme worked flawlessly for install. 

I've updated this PR, with a two-line change to those steps, replacing 

```
gem install jekyll
``` 

with:
 
```
gem install bundler
bundle install
```

That also worked with no other changes, so I think this is ready for your consideration. To test, you can check out my branch locally (be sure to ```git pull``` to get the latest version, checked in this morning), and run bundle install in the root of the project.

Thanks!

Jamie

**Comment by talbs** [comment]
Thanks for the pro-active help, @jamiefolsom. I'm trying to run through these steps locally and am getting stuck. Here's my local stacktrace...

```
ux-pattern-library :: (jamiefolsom-fix/jf/gh-pages-gem) » bundle install                                                                                                                                   ~/edX/ux-pattern-library

Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using RedCloth 4.2.9
Installing i18n 0.7.0
Installing json 1.8.3 with native extensions
Installing minitest 5.8.1
Installing thread_safe 0.3.5
Installing tzinfo 1.2.2
Installing activesupport 4.2.4
Installing addressable 2.3.8
Using blankslate 2.1.2.4
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Installing coffee-script-source 1.9.1.1
Installing execjs 2.6.0
Installing coffee-script 2.4.1
Using colorator 0.1
Installing ffi 1.9.10 with native extensions
Installing ethon 0.8.0
Installing gemoji 2.1.0
Installing net-dns 0.8.0
Installing public_suffix 1.5.1

Gem::InstallError: public_suffix requires Ruby version >= 2.0.
An error occurred while installing public_suffix (1.5.1), and Bundler cannot continue.
Make sure that `gem install public_suffix -v '1.5.1'` succeeds before bundling.
ux-pattern-library :: (jamiefolsom-fix/jf/gh-pages-gem) »                                                                                                                                               ~/edX/ux-pattern-library 5 ↵
ux-pattern-library :: (jamiefolsom-fix/jf/gh-pages-gem) » gem install public_suffix -v '1.5.1'                                                                                                          ~/edX/ux-pattern-library 5 ↵
ERROR:  Error installing public_suffix:
	public_suffix requires Ruby version >= 2.0.
```

Do I need to upgrade my version of Ruby? If so, how do I do that for this case using the virtualenvs equivalent you helped me set up?

Longer term questions, will anyone trying to install this project now have to have Ruby 2.0 installed locally? If so, how common is that (assuming my machine is a bit behind)?

**Comment by jamiefolsom** [comment]
Hi @talbs, 

It does appear that you're running into a dependency on a newer version of Ruby. As I recall, you installed rvm, but did you end up doing `rvm install 2.2`? That would probably solve the error you're seeing above.

More generally, to me it seems that you might want to identify and explicitly state all requirements of the developer's environment. My environment on the first hack day was woefully out of date, for example -- I'd be glad to dig into my versions of node, npm, bower and document what's required there.

Doing that, as long as it's not too painful for developers/designers to comply, would probably be a good way to avoid technical debt creeping into the UXPL and its docs, since you'd be confirming compatibility with github pages and your tool chain before they start work.

Completely up to you of course, but if I can help with that, let me know!

Jamie

**Comment by talbs** [comment]
@jamiefolsom, that did the trick, installing the bundle now. Thanks much.

- - -

> More generally, to me it seems that you might want to identify and explicitly state all requirements of the developer's environment. My environment on the first hack day was woefully out of date, for example -- I'd be glad to dig into my versions of node, npm, bower and document what's required there.

> Doing that, as long as it's not too painful for developers/designers to comply, would probably be a good way to avoid technical debt creeping into the UXPL and its docs, since you'd be confirming compatibility with github pages and your tool chain before they start work.

That all makes good sense to me. Any chance I can trouble you to update our README with another section similar to the table in https://github.com/edx/ux-pattern-library#third-party-dependencies with local development dependencies? 

If that's too much trouble, I can cover it separately. Thanks again!

**Comment by jamiefolsom** [comment]
@talbs, definitely, happy to do that. Probably will be a work in progress, of course, but glad to kick it off!

**Comment by talbs** [comment]
Sweet, thanks!

**Comment by talbs** [comment]
:+1: once the README is further updated. Thanks again for the good addition.

**Comment by jamiefolsom** [comment]
Hey @talbs, I hope to get this done over the weekend; if not: Monday. Have a nice weekend! :beers:

**Comment by jamiefolsom** [comment]
Hi @talbs, I've made those changes to the readme, and added some whitespace formatting to the tables for readability in markdown mode. Let me know if that's not the style you prefer, and if you have other thoughts, suggestions. Thanks!

**Comment by talbs** [comment]
@jamiefolsom, thanks. This looks great and I really appreciate the extra level of help in getting this all set up. I'm happy to :truck: this to Mergetown for  you.

**Comment by jamiefolsom** [comment]
Pleasure's mine -- thanks, @talbs!

**Pull request merged**
