### PR TITLE
Publish: Fixes + Favicon + Forms + Color Updates + Asset Managers

### PR DESCRIPTION
**Pull request by talbs**

### CODE REVIEW

**Comment by talbs** [comment]
@clrux and @marcotuts, mind reviewing and doing the honors of setting this :boat: out to :ocean: ?

**Comment by marcotuts** [comment]
I've not set up the PL locally it seems (or can't find where I did) Is there a doc I could follow to do so? Thanks for this PR!

**Comment by talbs** [comment]
Ahh, yep, check the README file - https://github.com/edx/ux-pattern-library/blob/master/README.md. Shout if you want an in-person walkthrough. Should be pretty quick.

**Comment by marcotuts** [comment]
:tada: :+1: This looks great! 

My only 2 nits would be with regards to the Copy section, but shouldn't block merge at all. The first was that the height of the example copy made it harder for me to get an at a glance view of the differences between the sections. One thought would be that if we're ok with just having one paragraph tag per copy style (lead, lead emphasized, lead de-emphasized), we could cut the height of this section in half. The other thing that could help would be to add at the beginning or end of the paragraph labels with the style classes / name. "(Copy Lead) Lorem Ipsum Dolor", or "End of Lorem Ipsum Para (Copy Lead De-Emphasized)"

:fireworks:

**Comment by talbs** [comment]
> My only 2 nits would be with regards to the Copy section, but shouldn't block merge at all. The first was that the height of the example copy made it harder for me to get an at a glance view of the differences between the sections. One thought would be that if we're ok with just having one paragraph tag per copy style (lead, lead emphasized, lead de-emphasized), we could cut the height of this section in half. The other thing that could help would be to add at the beginning or end of the paragraph labels with the style classes / name. "(Copy Lead) Lorem Ipsum Dolor", or "End of Lorem Ipsum Para (Copy Lead De-Emphasized)"

@marcotuts, good feedback. Happy to make those changes unless you wanna get your name on the contributor's list mad quick and make a PR against master. the file you'd be looking to edit is the Jekyll copy element post (https://github.com/edx/ux-pattern-library/blob/master/_posts/elements/2015-04-27-copy.md).

**Comment by marcotuts** [comment]
@talbs sure thing, I'll tackle those two nits in a PR against master, that makes sense to me!

**Comment by clrux** [comment]
Okay, the disabled enhanced select menu isn't actually disabled. You can give me today to work in a hotfix, or you can merge knowing I'll tackle this hotfix sometime in the near future. What do you think?

**Comment by talbs** [comment]
@clrux, sure, please get a hotfix PR in and I'll rebase to catch the fix before pushing this.

**Comment by clrux** [comment]
:+1:

**Pull request merged**
