### PR TITLE
Use Node Package Manager (npm)

### PR DESCRIPTION
**Pull request by talbs**
This work adds in a new way to consume the UXPL as a package (aside from Bower for the time being), using [Node.js](https://nodejs.org) and [node package manager](https://www.npmjs.com/). 

A few notes about this work:

* This is meant to be a prep step for using the UXPL within the Open edX platform and IDAs
* The package name (``edx-pattern-library``), license, and metadata have not changed from the previous bower settings
* ``.npmignore`` is a new file that acts like a ``.gitignore`` for our Node package, ignoring certain directories/files - this mirrors what we were ignoring with the Bower package configuration, FYI.
* Documentation (``README``) has been updated with new package instructions (in place of the Bower ones)
* I took the opportunity to lightly update third-party UXPL dependencies (not major versions).

- - -

#### Outstanding Issues/Concerns

* [ ] Right now, the UXPL source and its doc site are in this repo, with the doc site previously using the ``package.json`` file for its configuration (mostly for Gulp-based tasks). With the UXPL moving to using node, official configuration is now stored alongside the previous dependencies/gulp-workflow. Is this okay? Its the same debate around separating out the doc site/sandbox for new pattern development as before.
* [ ] The Node Package needs to be [published publicly](https://docs.npmjs.com/getting-started/publishing-npm-packages) to be used.
* [ ] We will not sunset the bower method of using the package until all current apps using that method are ported over. Cool?

- - -

#### Reviewers

* [ ] Front End Tooling - @andy-armstrong, @AlasdairSwan, and @dsjen
* [x] FED/Docs - @frrrances

### CODE REVIEW

**Comment by dsjen** [comment]
@talbs -- read over the changes and they look good to me!  You mention keeping the bower package up, which suggests that we'd remove that method for downloading the package.  Is it much work to register the package as both a node and bower package?  If not, it might be nice to provide it on both sites.

**Comment by talbs** [comment]
> Is it much work to register the package as both a node and bower package? If not, it might be nice to provide it on both sites.

@dsjen, thanks! Its not much work at all to support both. The set up and metadata for a Bower and Node package mirror each other a lot. All of our third party dependencies manage both, so I'm tempted to keep both with our preference being towards Node for our work.

I'll adjust the README to account for both (with our preference stated).

**Comment by talbs** [comment]
Okay, README (https://github.com/edx/ux-pattern-library/blob/talbs/use-npm/README.md) updated to support use of either package manager. :)

**Comment by frrrances** [comment]
:eyes: :+1: :car: :gift:

**Comment by talbs** [comment]
Thanks, all. I'm going to merge this to:

* test out publishing the package to the npm registry 
* try to use the published package in a separate repo/directory.

If others who haven't reviewed yet care to still, I'll follow-up on any feedback posted retroactively. I'll also let you know how those next steps go.

**Comment by talbs** [comment]
**Update**: 

* I've successfully published the ``edx-pattern-library`` as a public npm package - https://www.npmjs.com/package/edx-pattern-library
* I've successfully tested out using this npm package (replacing Bower) in our web-certs static repo. A PR has been made for the conversion - https://github.com/edx/web-certificates/pull/28

^ we should be good to go in using both bower and node to manage this source going forward. :)

**Pull request merged**
