### PR TITLE
PL Doc: Revamping Documentation Site Layout/UI

### PR DESCRIPTION
**Pull request by talbs**
WIP.

#### Known TODOs

* [ ] Use lists pattern for utility/pattern navigation
* [ ] Link to permalink pattern pages from navigation
* [ ] Visually flatten UXPL Doc Site UI as much as possible (use white edX header, make sidebar/nav less strong, remove white background from patterns)
* [ ] Create new landing index template/page for UXPL - intro to the project, status, how to use, recent patterns/work completed, etc.

- - -

#### Inspiration

image

### CODE REVIEW

**Comment by talbs** [comment]
@dsjen and @andy-armstrong, here's the extracurricular branch/PR I made for updating the UXPL Doc Site UI (pre-official landing story). There's still plenty to do and I've made some notes about TODOs I had this branch in mind for as well as the visual inspiration/comp that started this work.

This has been rebased and should be good to work on. Shout if you have questions.

**Comment by dsjen** [comment]
Thank you!  I'll check it out and be in touch with questions.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @talbs! I've created [OSPR-1113](https://openedx.atlassian.net/browse/OSPR-1113) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
I'll delete the OSPR ticket....

**Comment by talbs** [comment]
Thanks, @nedbat.

FYI, @andy-armstrong and @dsjen, I'm going to close this PR as you guys have #290 started and can continue from there. I've left a note about where this work was going as part of that thread. Feel free to delete this branch if you don't need it any longer as well.

**Pull request closed without merging**
